# -*- mode: ruby -*-
# vi: set ft=ruby :

# simple vagrant file for ctfs

Vagrant.configure("2") do |config|

  # 1) OS-flavor system/network properties
  config.vm.box = "bento/debian-9.5"
  # config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "private_network", ip: "10.0.10.2"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end

  # 2) Dependencies
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y && apt-get upgrade -y && apt-get autoremove -y

    apt install -y nginx
  SHELL

  # 3) Deployment
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo service nginx start
  SHELL

end
