# -*- mode: ruby -*-
# vi: set ft=ruby :

# A vagrantfile for gui debian9.  Also installs
# a gui program for analyzing IQ files

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-9.5"
  # config.vm.box = "bento/ubuntu-18.04"

  # set memory limit
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--memory", "6024"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  # alway pull updates on startup
  config.vm.provision "shell", run: "always", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y && apt-get upgrade -y && apt-get autoremove -y
  SHELL

  # provision/config
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive

    apt-get update -y && apt-get upgrade -y
    apt-get install -y gnome

  SHELL

  # provision/config
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    cd $HOME
    wget http://www.baudline.com/baudline_1.08_linux_x86_64.tar.gz
    tar xf baudline_1.08_linux_x86_64.tar.gz
  SHELL

end
